package:
  name: market_py2cpp
  version: 0.0.1

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja

  host:
    - python
    - pip

  run:
    - python


test:
  requires:
    - pytest
  imports:
    - market_py2cpp
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: Experimental prototype to be refactored.
  license_file: LICENSE
